### ISSUE TITLE
what is the <string name="client_static_keypair_enc"> in keystore.xml?how to decrpt it?

### ISSUE THREAD

**Issue by andersling** [kaisar945/yowsup-config-extract#2]
Hi,sir ! Big thanks for your great sharing!! It is so awsome !!

By the way, I found that there are 2 client static keypairs in the keystore.xml :
A: <string name="client_static_keypair_enc"> the array only has **3 fields** with the array[0] **type=0** 
and 
B: <string name="client_static_keypair_pwd_enc"> the array has **5 fields** with the array[0] **type=2**

What are the difference between them? Does yowsup **only need B** not A?
And how to decrpt A?

Thanks a lot! and hope you can do me a favor to give some tips ,sir!

**Comment by kaisar945** [comment]
Yes, I also found that there are 2 client static keypairs in the keystore.xml, I don't know how to use A, but I'm sure yowsup only needs B. I guess the decryption method of A and B is the same but I don't know the specific purpose of A
